### ISSUE TITLE
What is https://dev-authoring.ihtsdotools.org/config?

### ISSUE THREAD

**Issue by tandara0** [IHTSDO/authoring-ui#16]
Hello.

I am trying to setup Snomed Authoring Platform.
Until now, I have successfully installed and linked authoring service, authoring ui, jira, crowd and IMS so far.

But I still failed to get /config/version.
In the nginx.conf, the location /config is proxy to https://dev-authoring.ihtsdotools.org/config, which is not working, of course.
Like other locations in the nginx.conf, this location may be one of the IHTSDO services.
But I cannot even guess which one is config service in this IHTSDO open source repository.

Thank you.

**Comment by Chris-Swires** [comment]
Hey @tandara0 

I'll get the readme updated for you during this development cycle, however for now the configuration there has been updated to:

location /config { alias /opt/authoring-ui/conf; }

(And the authoring-ui is calling /config/versions.json - so the file explicitly)

That in our case routes to a file containing our deployed application versions at the point of deployment. This is generated by our rundeck deployment job, and so may not be relevant to your stack. 

Chris
