### ISSUE TITLE
No repository found for release-notes 

### ISSUE THREAD

**Issue by someshwarMirge** [IHTSDO/authoring-ui#17]
We are deploying Snomed CT authoring platform in our facility. We are stuck in deployment as we are unable to find the repository of 'release-notes' service.
We have found that this service APIs has been called multiple times from authoring UI e.g. lineitems API call (attached screenshot for the same). 
We need help regarding, 
1.Where to find release-notes Service repository.
2. It's deployment strategy. 

![image](https://github.com/IHTSDO/authoring-ui/assets/45324312/3849be0a-dbb0-4822-b9fa-a2e01c151542)

**Comment by kaicode** [comment]
The Release Notes Service is one of the newer microservices and it looks like the GitHub repository has not been made public yet. Please accept our apologies. I have started our internal process to make the repo public, it usually takes a few days. I'll post a link here when it's ready.

**Comment by kaicode** [comment]
The Release Notes Service repository is now public, here: https://github.com/IHTSDO/release-notes-service .
The readme contains deployment and configuration notes. Note that the readme says the service requires a different version of Elasticsearch than the one Snowstorm uses at this time. I'm not sure what the rationale for this is.

**Comment by someshwarMirge** [comment]
Thanks @kaicode for the support! We are able to deploy the service successfully.
