### ISSUE TITLE
Build failure.

### ISSUE THREAD

**Issue by CodeMatsku** [IHTSDO/authoring-ui#6]
Not sure what I'm doing wrong...
I confirmed that I had the right karma versio. The other thing is the "yeoman-maven-plugin" I couldn't see any reference to it in your git page but should I be considered?

PS C:\test> mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------< org.ihtsdo.otf:authoring-ui >---------------------
[INFO] Building IHTSDO Single Concept Authoring Web Front End Angular 6.10.2
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ authoring-ui ---
[INFO]
[INFO] --- yeoman-maven-plugin:0.2:build (run-grunt) @ authoring-ui ---
[INFO] node version :
v14.15.5
[INFO] npm version :
7.5.4
[INFO] --------------------------------------
[INFO]          NPM INSTALL
[INFO] --------------------------------------
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: angularapptemplate@0.0.0
npm ERR! Found: karma@0.13.22
npm ERR! node_modules/karma
npm ERR!   karma@"~0.13.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer karma@"^4.0.0 || ^5.0.0" from grunt-karma@4.0.0
npm ERR! node_modules/grunt-karma
npm ERR!   grunt-karma@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\---\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\---\AppData\Local\npm-cache\_logs\2021-02-18T18_41_51_670Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.233 s
[INFO] Finished at: 2021-02-18T20:41:51+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.trecloux:yeoman-maven-plugin:0.2:build (run-grunt) on project authoring-ui: Error during : cmd /c npm install: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
PS C:\test>

**Comment by Chris-Swires** [comment]
Hey @CodeMatsku 

Checking here both locally and through our build server I'm not able to replicate the issue, however I notice that I'm locally running node: v12.18.2 and npm: v6.14.5 - it could be that the major version changes in the supporting frameworks has shifted the dependency tree. I'll update my local packages and see if we can harden the tree but it may take us a few days to get there. 

As a work around you could try setting your node and npm versions to the above until such a time as we're able to replicate.

**Comment by CodeMatsku** [comment]
thx, I'll try that

**Comment by CodeMatsku** [comment]
I made the version chages and it works fine now, Thank you for helping.
